{
  ------------------------------------------------------------------------------
  JsonFlow Configuration Include File
  ------------------------------------------------------------------------------
}

// Uncomment the line below to enable Stratum integration
// (Metrics, Advanced Caching, Detailed Reports)
{$DEFINE USE_STRATUM}

// Other configuration directives can be added here
// {$DEFINE DEBUG_MODE}
